### ISSUE TITLE
Document versioning

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_documentation#35]
Is there a plug-in to have mutliple version of a page? For example. If I have 3 product version:

- 1.0.0
- 1.2.0
- 1.3.1

I'd like to have a drop down for each documentation page, which allow you to switch to a different version of the page, so if the user has version 1.0.0 he can still read the documentation for that version.

**Comment by acidbiscuit** [comment]
Yes, it is possible.

We would have to place create a dropdown for every product with available versions and add/edit every page manually.

Same like on [this][https://vcalendar.io/] page for API section.

**Comment by davidgatti** [comment]
OK, and how would we then manage the different version of the files?

**Comment by acidbiscuit** [comment]
@davidgatti Manually, since every version will have it's own file.

**Comment by davidgatti** [comment]
ok, in this case can we do a folder which represents the product, and inside there will be `1.0.0.md`, 11.3.0.md` ecc?

**Comment by acidbiscuit** [comment]
@davidgatti That is correct.

**Comment by davidgatti** [comment]
OK, cool, in this case lets do it :)
