### ISSUE TITLE
Missing Edit on Github URL

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_documentation#37]
Each page should have a `Edit on GitHub` URL. I think it be nice to have this URL in the top right corner of the page, where now it sayes `GitHub`, instead at the end of a page.

**Comment by acidbiscuit** [comment]
@davidgatti There is no option to display edit link on top of the page. Custom development would be required.

**Comment by davidgatti** [comment]
OK, in this case this is OK, bellow, but fix the URL :)
