### ISSUE TITLE
Add the correct colors

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_documentation#50]
Maybe this is to generic, but see if you can extrapolate
[Colors AWS product pages.pdf](https://github.com/0x4447-office/0x4447_webpage_documentation/files/6371960/Colors.AWS.product.pages.pdf)
 which color to set on the text on the page based on the attached PDF.

**Comment by acidbiscuit** [comment]
@davidgatti 

#0e67d7 accent color for light mode  
#219dff accent color for dark mode

**Comment by davidgatti** [comment]
Cool then update the page with those.
