### ISSUE TITLE
Last edit disappeared 

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_documentation#55]
The time stamp of the last edit did disappear.

**Comment by acidbiscuit** [comment]
@davidgatti Can't reproduce. Can you double check in master branch, please?

**Comment by davidgatti** [comment]
I'm trying to hard refresh like crazy and still nothing. Is there a command that needs to be run to create those dates? Or how dose that feature even work? where do they get the date?

![Screen Shot 2021-04-28 at 8 09 10 AM](https://user-images.githubusercontent.com/411114/116354672-0a833b80-a7f9-11eb-8175-d1f6ee46e7ea.png)

**Comment by acidbiscuit** [comment]
@davidgatti The plugin takes the dates from git file information during build time.

**Comment by davidgatti** [comment]
aaaa ok, in this case you can remove the plugin, it won't work how I build the site on AWS.
