### ISSUE TITLE
How to switch version

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_documentation#65]
Once issues #60 is done, and you go in to a product docs, next to the Product menu (to the left) there should be a version drop donw, where you can select the version fo the docs you want to see, and it be nice if you switch version for the rop down to reflect that.

![Screen Shot 2021-05-15 at 3 23 38 PM](https://user-images.githubusercontent.com/411114/118363342-2b3ae780-b594-11eb-8563-196ed3b99036.png)

**Comment by acidbiscuit** [comment]
@davidgatti If I understand correctly, on specific product page we should display "Versions" menu link with a dropdown of available versions. This menu should not be visible if page is not a product, right?

**Comment by davidgatti** [comment]
Correct.

**Comment by davidgatti** [comment]
Closed by mistake

**Comment by acidbiscuit** [comment]
@davidgatti There is no supported configuration for dynamic navbar for Vuepress. We would have to come up with hacky solution for this one. Also, please note, that dynamic dropdown content for versions will introduce inconsistent app level navigation, which may be confusing for users.

**Comment by davidgatti** [comment]
Just to make sure we understand each other at a distance, this is what I'm trying to explain. 

![Screen Shot 2021-05-24 at 5 21 33 AM](https://user-images.githubusercontent.com/411114/119292067-f3950500-bc4f-11eb-9ca8-bb37b8b2285f.png)

**Comment by acidbiscuit** [comment]
@davidgatti Right. It works perfectly for single product version, but requires different approach when multiple product version lines exist. Different approach both technically and in term of UX.

**Comment by davidgatti** [comment]
OK, lets pause this for a moment.

**Comment by davidgatti** [comment]
Skipping since the framework won't support this by default.
