### ISSUE TITLE
Line numbers only for selected code sections?

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_documentation#66]
Based on the docs, you can set the code section to have line numbers: https://vuepress.vuejs.org/guide/markdown.html#line-numbers - is it possible to have line numbers for just selected code block and not for all of them?

**Comment by acidbiscuit** [comment]
@davidgatti It is not possible via Vuepress configuration, but there is a [workaround](https://github.com/vuejs/vuepress/issues/1909). With additional CSS styles, line number will be hidden by default, but it will be possible to display them like this:

``` {.line-numbers}
text with
line numbers
```

Will this work for you?

**Comment by davidgatti** [comment]
definitely
