### ISSUE TITLE
Mark down components?

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_documentation#67]
Not sure if this can be done, but I did find this section in the documentation  https://vuepress.vuejs.org/guide/markdown-slot.html. You did already a component with the cloudformation section, but I wonder, can this be done with markdown? I'd like to write markdown in a components, and have it be set at build time in the main doc. I have lots of repetitive sections across the pages.

**Comment by acidbiscuit** [comment]
@davidgatti Markdown slots allow you to configure layout components. Can you give me an example of a problem you want to solve?

**Comment by davidgatti** [comment]
FOr example each product page has the yellow not as the top of the page, and is identical on all prodcut page, I want to have that note in one file and used it across all pages.

**Comment by acidbiscuit** [comment]
@davidgatti Then yes, optional layout level slots can help with that.

**Comment by davidgatti** [comment]
Eppic, so make one so I can see how it is done, and then I will do the rest. Make that yellow note at the top of each page.

**Comment by davidgatti** [comment]
Closing the issues since it can't be done how I'd like it to be done.
